### ISSUE TITLE
Latest python doesn't have ssl.PROTOCOL_SSLv3

### ISSUE THREAD

**Issue by sbrun** [andresriancho/w3af#9108] opened 2015-03-25 14:35 UTC
Hi,
We are working on a new version of kali based on debian jessie. But with the new version of python packages (debian jessie) ssl.PROTOCOL_SSLv3 attribute doesn't exist anymore. w3af fails to start:
```
Traceback (most recent call last):
  File "/usr/share/w3af/w3af_gui", line 97, in <module>
    _main()
  File "/usr/share/w3af/w3af_gui", line 93, in _main
    sys.exit(main())
  File "/usr/share/w3af/w3af_gui", line 87, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/usr/share/w3af/w3af/core/ui/gui/main.py", line 38, in <module>
    from w3af.core.controllers.w3afCore import w3afCore
  File "/usr/share/w3af/w3af/core/controllers/w3afCore.py", line 37, in <module>
    from w3af.core.controllers.core_helpers.strategy import w3af_core_strategy
  File "/usr/share/w3af/w3af/core/controllers/core_helpers/strategy.py", line 30, in <module>
    from w3af.core.data.url.extended_urllib import MAX_ERROR_COUNT
  File "/usr/share/w3af/w3af/core/data/url/extended_urllib.py", line 39, in <module>
    import opener_settings
  File "/usr/share/w3af/w3af/core/data/url/opener_settings.py", line 40, in <module>
    from w3af.core.data.url.handlers.keepalive import HTTPHandler as kAHTTP
  File "/usr/share/w3af/w3af/core/data/url/handlers/keepalive/__init__.py", line 40, in <module>
    from .connections import (ProxyHTTPConnection, ProxyHTTPSConnection,
  File "/usr/share/w3af/w3af/core/data/url/handlers/keepalive/connections.py", line 12, in <module>
    from w3af.core.data.url.openssl.ssl_wrapper import wrap_socket
  File "/usr/share/w3af/w3af/core/data/url/openssl/ssl_wrapper.py", line 23, in <module>
    PROTOCOL_SSLv3 = ssl.PROTOCOL_SSLv3
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

Just for information you can look at https://bugs.kali.org/view.php?id=2160 (there was the same issue)
thanks

**Comment by andresriancho** [comment] 2015-03-25 16:47
Thanks for helping us keep the kali package up to date, I've fixed the issue at https://github.com/andresriancho/w3af/commit/a6b6c6750ed0a6e18461416ea9e613e6278eef6a , tests are running https://circleci.com/gh/andresriancho/w3af/1666. Will let you know if this is fixed or not in a few minutes.

**Comment by andresriancho** [comment] 2015-03-25 16:54
Tests did not PASS, will have to look at this tomorrow.

**Comment by andresriancho** [comment] 2015-04-03 22:45
PROTOCOL_SSLv23 and PROTOCOL_SSLv3 , those two dissapear? Need to double check
```
[pedro:~/pch/w3af] [w3af] develop ± find . -name '*.py' -type f | xargs egrep 'ssl\.PROTOCOL_SSLv(2|3)3'
./w3af/core/data/url/tests/test_xurllib.py:        ssl_daemon = RawSSLDaemon(Ok200Handler, ssl_version=ssl.PROTOCOL_SSLv23)
./w3af/plugins/audit/ssl_certificate.py:                                       ssl_version=ssl.PROTOCOL_SSLv23)
./w3af/plugins/audit/ssl_certificate.py:            ssl_sock = ssl.wrap_socket(s, ssl_version=ssl.PROTOCOL_SSLv23)
./w3af/plugins/audit/ssl_certificate.py:                                       ssl_version=ssl.PROTOCOL_SSLv23)
```

**Comment by andresriancho** [comment] 2015-04-03 22:59
`sudo docker run -it debian:jessie /bin/bash` will help me identify protocols available in the latest python at jessie distribution

**Comment by andresriancho** [comment] 2015-04-03 23:23
PROTOCOL_SSLv23 does exist in jessie:

```python
>>> import ssl
>>> ssl.PROTOCOL_SSLv23
2
>>> ssl.PROTOCOL_SSLv3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
>>> 
```

**Comment by andresriancho** [comment] 2015-04-04 13:33
Confirmed as fixed in https://github.com/andresriancho/w3af/tree/develop . Will merge to master in a while, the next Kali package we build will have these changes included.

@sbrun is there any rush to build a new w3af.deb for kali with these changes?

**Comment by andresriancho** [comment] 2015-04-04 13:34
Please add your comment, if it requires any action I'll create another issue

**Comment by sbrun** [comment] 2015-04-07 13:33
There will be a release very soon of a beta version of kali based on debian jessie. 
For the beta test maybe we can use a snapshot of github or just apply a patch with the commit fixing the bug.

**Comment by andresriancho** [comment] 2015-04-07 15:11
I've merged develop into master and tagged it as `1.6.49` to help you with packaging.

There are [two new dependencies](https://github.com/andresriancho/w3af/blob/master/w3af/core/controllers/dependency_check/requirements.py#L56-L57) to be referenced from the w3af.deb:
```python
                     PIPDependency('vulndb', 'vulndb', '0.0.17'),
                     PIPDependency('markdown', 'markdown', '2.6.1')]
```

 * https://pypi.python.org/pypi/vulndb/0.0.17 which is something I've worked on and I'm 100% sure it's not in Debian/Ubuntu repos
 * https://pypi.python.org/pypi/Markdown/2.6.1 which might already be in Debian repos

**Comment by sbrun** [comment] 2015-04-10 13:29
Hi
I packaged the version 1.6.49. It's available in kali-proposed-updates (python-vulndb too).
I didn't update python-markdown: the version in kali is 2.1.1 and in future kali release based on jessie is 2.5.1
Could you test in kali if it's ok?

**Comment by andresriancho** [comment] 2015-04-10 14:16
* Found [python-vulndb](http://pkg.kali.org/pkg/python-vulndb) 0.0.17
 * Don't see 1.6.49 at http://pkg.kali.org/pkg/w3af , should it appear there?

I believe that 2.5.1 will be ok to use in the latest release. Will test in a while.

**Comment by sbrun** [comment] 2015-04-10 14:27
The new version of w3af has been uploaded today. http://pkg.kali.org/pkg/w3af will be automatically updated in few hours.

**Comment by andresriancho** [comment] 2015-04-10 18:26
@sbrun is there a guide on how to beta-test the latest kali (the one built on top of debian jessie)?

**Comment by sbrun** [comment] 2015-04-13 07:22
Hi,
There is no guide. You can download a ISO here: http://archive.kali.org/kali-daily-images/
(kali-linux-rolling ISO are based on debian jessie)
If you find bugs, you can report them on the bug tracker kali and choose Product Version: "kali-rolling"

**Comment by andresriancho** [comment] 2015-04-13 11:18
Ok, downloading.

**Comment by andresriancho** [comment] 2015-04-14 10:56
I've been unable to confirm the fix using the ISO in virtualbox. I've tried in two different PCs, both using ubuntu 14.04 as host and the latest virtualhost. The issue is the same in both: Kali freezes inside virtualbox. The freeze occurs any time between 1 and 5 minutes after starting the VM. Have you experienced this in the past?

**Comment by andresriancho** [comment] 2015-04-14 10:59
Going to try with vmware

**Comment by andresriancho** [comment] 2015-04-14 11:20
Same issue with vmware. While I try to `apt-get update; apt-get upgrade -y` the vm freezes.

**Comment by andresriancho** [comment] 2015-04-14 11:46
Increased RAM to 1GB and upgrade was successful, but w3af doesn't start. Increasing again.

**Comment by andresriancho** [comment] 2015-04-14 12:15
Everything seems to be working as expected

**Closed by andresriancho** 2015-04-14 12:15 UTC
Labels: bug, priority:high
