### ISSUE TITLE
too many consecutive errors

### ISSUE THREAD

**Issue by graytips** [andresriancho/w3af#9073] opened 2015-03-23 17:21 UTC
How can I address the following issues..

My connection is 4mbps

**IMPORTANT** The following error was detected by w3af and couldn't be resolved:
w3af found too many consecutive errors while performing HTTP requests. In most cases this means that the remote web server is not reachable anymore, the network is down, or a WAF is blocking our tests. The last exception message was "HTTP connection pool (keepalive) waited too long (6.25 sec) for a free connection, giving up. This usually occurs when w3af is scanning using a slow connection, the remote server is slow (or applying QoS to IP addresses flagged as attackers)." (ConnectionPoolException). - Reason: HTTP connection pool (keepalive) waited too long (6.25 sec) for a free connection, giving up. This usually occurs when w3af is scanning using a slow connection, the remote server is slow (or applying QoS to IP addresses flagged as attackers).

// W3af version details...
 Python version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.45
    Revision: b7cffaa62a - 26 Feb 2015 13:30

**Comment by andresriancho** [comment] 2015-03-24 00:29
@graytips getting the same issue with the latest w3af from master? I've modified the error handling a little bit between 1.6.45 and 1.6.48

**Comment by graytips** [comment] 2015-03-24 05:05
Yes it is the same error... with latest version also..

**Comment by andresriancho** [comment] 2015-03-24 13:34
Can you share the target URL? As the error says, it might be that the target is detecting the scan as an attack and closing some connections / slowing down responses.

Also, it could be a w3af error, in which case I can fix it (hopefully quickly) since I've been working on this code section in the last month

**Comment by andresriancho** [comment] 2015-03-25 10:31
Running a scan myself

**Comment by andresriancho** [comment] 2015-03-25 10:35
Not getting the error shown by @graytips (for now), but noticed `server: Apache/2.2.27 (Unix) mod_ssl/2.2.27 OpenSSL/1.0.1e-fips mod_mono/2.6.3 mod_bwlimited/1.4` , maybe `mod_bwlimited` has something to do with this?

**Comment by andresriancho** [comment] 2015-03-25 10:37
Found some timeouts during the scan, but the extendedurllib error rate is <3%

Running a second scan at the same time to try to force more errors

**Comment by andresriancho** [comment] 2015-03-25 10:57
@graytips sent w3af script for testing, running that too.

My three scans using GUI and the mentioned configuration finished successfully

**Comment by andresriancho** [comment] 2015-03-25 10:59
Nothing strange found at wireshark packet capture

**Comment by andresriancho** [comment] 2015-03-25 11:02
@graytips how many minutes into the scan do you get the error?

Do you know/have a way of verifying if your ISP has some filters set?

**Comment by andresriancho** [comment] 2015-04-11 23:39
Closing since @graytips is not answering.

Please add more comments if this issue can still be reproduced and I'll gladly help debug and fix the issue.

**Closed by andresriancho** 2015-04-11 23:39 UTC
Labels: bug, core, priority:low

**Comment by graytips** [comment] 2015-04-12 05:12
Hello,

Now I am unable reproduce the bug, if something comes up. Will update you :)

Regards,
Shafeeque Olassery Kunnikkal C|EH,C|EI
Graytips Cyber Technologies | www.graytips.com
