### ISSUE TITLE
w3af hangs when performing full_audit 

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#659] opened 2013-09-29 07:54 UTC
## User description
W3af starts scanning in full_audit mode, but the scan never ended even after 24 hrs and it gets hung at the same step again and again and I can see the following when I Ctrl+C.

> **IMPORTANT** The following error was detected by w3af and couldn't be resolved:
Extended URL library error '[Errno 111] Connection refused' while requesting 'https://192.168.52.137/index.php'.

Under log tab its stuck at this 

> "The most accurate fingerprint for this HTTP server is: "Apache/2.2.9 (Debian) PHP/5.2.6-2 with Suhosin-Patch mod_python/3.3.1 Python/2.5.2 mod_perl/2.0.4 Perl/v5.10.0". This information was found in the request with id 1.

After that there are no logs 

## What operating system are you using?

Kali Linux, using w3af 1.6 downloaded from git repository

## Contact information

The user provided the following email address for contact: legolas.aoe2@gmail.com

# Version Information
```
  Python version: 2.7.3 (default, Jan  2 2013, 16:53:07) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6
    Revision: 3ef1aa4e9e - 25 Sep 2013 13:10
    Author: Andres Riancho and the w3af team.
```

**Comment by andresriancho** [comment] 2015-02-26 15:04
The issue, as reported by `legolas.aoe2@gmail.com`, is not something I can reproduce thus I can't fix it.

@marrowsmith @VICKERSFRANK @leafonsword any of you have a way for me to reproduce this issue in the latest w3af? I would love to find a way to reproduce it, which will lead to a quick fix which will benefit the whole user base.

If we can't figure out a way to reproduce it, I'll have to close this issue :-1: , not because I believe it's not real, but because I can't fix something that I can't see.

**Comment by andresriancho** [comment] 2015-03-04 12:25
Closing

**Closed by andresriancho** 2015-03-04 12:25 UTC
Labels: bug, priority:medium

**Comment by Sir-Fancy** [comment] 2016-06-10 23:15
I'm having this issue as well on Kali Linux 2.0. [Here's what's shown in console](https://gist.github.com/Sir-Fancy/1d2874c55af6f97c94ded67fb5524032), but the GUI is frozen at the start of the scan and must be killed.
