### ISSUE TITLE
Howto: Solve "Unknown key" issue

### ISSUE THREAD

**Issue by sectest667** [andresriancho/w3af#17312] opened 2018-10-08 14:10 UTC
Hey folks,
if you run w3af with the option "-s" (eg from a Jenkins job) and all you see in your logs are trillion lines of 

```
Unknown key. The following commands are allowed during the scan:


  (P) pause the scan

  (R) resume a paused scan

  (enter) print scan status

  (Ctrl+C) stop scan
```

it might help to change how you start w3af.

In my case I had to add the option "-tt" (yes, two t's) to ssh like that:

```
ssh -tt ${tuser}@${thost} "source ${virtenv} && \
    ${w3afbin} -s ${sdir}/webapp_phase02.w3af"
```

Hope that helps, happy hackin'! :)
sectest667

**Comment by andresriancho** [comment] 2018-10-09 21:35
Hmmm... it seems that the problem is that you're not running w3af in a "real terminal", and you're fixing it with `ssh`:

```
     -t      Force pseudo-terminal allocation.  This can be used to execute arbitrary screen-based programs on a remote machine, which can be very useful, e.g. when implementing menu services.  Mul‐
             tiple -t options force tty allocation, even if ssh has no local tty.
```

**Comment by andresriancho** [comment] 2018-10-09 21:37
Same issue here https://github.com/andresriancho/w3af/pull/17235

**Comment by andresriancho** [comment] 2018-10-09 21:39
Latest merge from develop to master should fix this issue.

Please try `git pull` in your w3af installation, run again, issue should be fixed.

**Closed by andresriancho** 2018-10-09 21:39 UTC
