### ISSUE TITLE
[Auto-Generated] Bug Report - Output to html crashes - 'utf8' codec can't decode byte 0x80

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#8688] opened 2015-03-04 11:14 UTC
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?

What operating system are you using?
Lubuntu 12.10 Desktop

Please provide any additional information below:

## Version Information
```
  Python version: 2.7.8 (default, Oct 20 2014, 15:05:19) [GCC 4.9.1]
  GTK version: 2.24.25
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.45
    Revision: b7cffaa62a - 26 Feb 2015 13:30
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/home/user/tools/w3af/w3af/core/ui/gui/main.py", line 609, in start_scan_wrap
    real_scan_start()
  File "/home/user/tools/w3af/w3af/core/ui/gui/main.py", line 600, in real_scan_start
    self.w3af.start()
  File "/home/user/tools/w3af/w3af/core/controllers/w3afCore.py", line 235, in start
    self.scan_end_hook()
  File "/home/user/tools/w3af/w3af/core/controllers/w3afCore.py", line 423, in scan_end_hook
    om.manager.end_output_plugins()
  File "/home/user/tools/w3af/w3af/core/controllers/output_manager/manager.py", line 138, in end_output_plugins
    self.__end_output_plugins_impl()
  File "/home/user/tools/w3af/w3af/core/controllers/output_manager/manager.py", line 149, in __end_output_plugins_impl
    o_plugin.end()
  File "/home/user/tools/w3af/w3af/plugins/output/html_file.py", line 308, in end
    severity))
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 711: invalid start byte

```
## Enabled Plugins
```python
{'attack': {},
 'audit': {},
 'auth': {},
 'bruteforce': {},
 'crawl': {},
 'evasion': {},
 'grep': {},
 'infrastructure': {},
 'mangle': {},
 'output': {}}

```

**Comment by DavidKutik** [comment] 2015-03-04 11:24
Hey
the error is raised when html-report output file name is:
~/w3af_owasp_top10_report_3.html
it isn't raised when it's
~/result1.html

**Comment by andresriancho** [comment] 2015-03-04 11:26
Duplicate of html output file - UnicodeDecodeError: 'utf8' codec can't decode byte #4219

**Comment by andresriancho** [comment] 2015-03-04 11:27
@DavidKutik are you 100% sure about the filename stuff? Have you tested more than once? Can you reproduce the issue each time you run the scan? If so, could you please send me the instructions to reproduce it myself?

**Comment by andresriancho** [comment] 2015-03-04 11:28
@DavidKutik please answer as a comment at #4219 , closing this issue because it's a dup

**Closed by andresriancho** 2015-03-04 11:28 UTC
