### ISSUE TITLE
Python 3 migration

### ISSUE THREAD

**Issue by XVilka** [andresriancho/w3af#18221] opened 2019-11-22 05:22 UTC
Python 2 is dead in a month, and many distributions started to remove python2 packages already. It makes sense to start the migration.

https://pythonclock.org/

**Comment by andresriancho** [comment] 2019-11-25 13:37
Duplicate of https://github.com/andresriancho/w3af/issues/17866

**Closed by andresriancho** 2019-11-25 13:37 UTC
