### ISSUE TITLE
Can't run script with docker console

### ISSUE THREAD

**Issue by flacidsnake** [andresriancho/w3af#16479] opened 2018-01-17 10:35 UTC
Hi,

I'm using debian 9 and installed w3af through docker. Everything works fine.

But, when I try to execute the script (with a modified target) at:
https://www.owasp.org/index.php/Automated_Audit_using_W3AF
I get an error.

This is the command:
sudo ./w3af_console_docker -s auditoria.w3af
This is the error:
w3af_console_docker: error: unrecognized arguments: -s auditoria.w3af

Any help?
Regards

**Comment by andresriancho** [comment] 2018-01-24 16:19
This is a duplicate of https://github.com/andresriancho/w3af/issues/8461

**Comment by andresriancho** [comment] 2018-01-24 16:20
Summary: at least until https://github.com/andresriancho/w3af/issues/8461 is not completed, what you want to do can't (easily) be done.

You could edit the w3af_console_docker code to get this done.

**Closed by andresriancho** 2018-01-24 16:19 UTC
